BitBucket pipelines: Speedup e2e tests
Changes:
* Reduce how long it takes to run e2e tests.
* Pull all images in parallel.
* Define e2e tests image in the `docker-compose.yml`.
* Remove e2e run script in favour of `docker-compose run e2e`.

---

REFAPP-399
As a Product Owner, I require CI to be moved to BitBucket Pipelines so it can be better-supported internally by OBIE.
https://openbanking.atlassian.net/browse/REFAPP-399

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -1,8 +1,8 @@
 clone:
   depth: 1
-
 options:
   docker: true
+image: docker/compose:1.22.0
 
 definitions:
   caches:
@@ -41,6 +41,25 @@ pipelines:
             artifacts:
               - e2e/artifacts/**
             script:
+              # print logs from the container when a failure happens
+              - |
+                print_logs() {
+                  echo -e "\\033[92m  ---> logs reference-mock-server ... \\033[0m";
+                  docker logs reference-mock-server;
+
+                  echo -e "\\033[92m  ---> logs ob-api-proxy ... \\033[0m";
+                  docker logs ob-api-proxy;
+
+                  echo -e "\\033[92m  ---> logs compliance-suite-server ... \\033[0m";
+                  docker logs compliance-suite-server;
+
+                  echo -e "\\033[92m  ---> logs zookeeper ... \\033[0m";
+                  docker logs zookeeper;
+
+                  echo -e "\\033[92m  ---> logs kafka ... \\033[0m";
+                  docker logs kafka;
+                }
+                trap print_logs 0 1
               - apk add --no-cache bash git # install bash and git and pip
               - |
                 export ENV="circleci"
@@ -59,10 +78,12 @@ pipelines:
                 export GOOGLE_OAUTH_CLIENT_SECRET="<anything>"
               - ./scripts/create-envs.sh
               - ./scripts/build-reference-mock-server.sh
+              # pre-pull images in parallel
+              - docker-compose pull --include-deps --parallel e2e reference-mock-server mongo redis kafka zookeeper
               - docker-compose up -d --build kafka mongo redis reference-mock-server ob-api-proxy
-              - ./scripts/wait-for-kafka.sh
               - docker-compose up -d --build compliance-suite-server
-              - ./scripts/run-e2e.sh
+              - echo -e "\\033[92m  ---> sleeping (10 seconds) ... \\033[0m" && sleep 10s
+              - docker-compose run e2e
 
         - step:
             name: services/ob-api-proxy
